config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'
  get 'dashboard/index'
  get 'dashboard/import'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include Pay::Billable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :pwned_password,
         :omniauthable, omniauth_providers: [:stripe_connect]
validates :email, presence: true



  def can_receive_payments?
    uid? && provider? && access_code? && publishable_key?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def import
    @user = current_user
    @customers = Stripe::Customer.list({limit:10000}, {stripe_account: @user.uid})

    api_key = 'keyLZIThxuV5cFgBe'
    app_key = 'appUoEvPb7XuhjCUs' #called base id in airtable
    table_name = 'stripe_customers'

    airtable =  Airrecord.table(api_key, app_key, table_name)
    @customers.auto_paging_each do |c|
      row = airtable.create(
        "Stripe Id": c['id'],
        "Description": c['description'],
        "Created At": c['created'],
        "Name": c['name'],
        "Email": c['email']
      )
    end
  end



end

app/controllers/omniauth_callbacks_controller.rb
# app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController


  end

app/helpers/application_helper.rb
module ApplicationHelper
    def stripe_url
        "https://connect.stripe.com/oauth/authorize?response_type=code&client_id=#{Rails.application.credentials.dig(:stripe, :connect_client_id)}&scope=read_write"
    end

    def stripe_connect_button # add this method
        link_to stripe_url, class: "btn-stripe-connect" do
          content_tag :span, "Connect with Stripe"
        end
    end

end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

<p><%= link_to "import stripe customers", dashboard_import_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stripesheets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <%= render 'shared/navigation' %>
<div class="container mt-3">
	  <%= yield %>
</div>

  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">
    <button aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarMain" data-toggle="collapse" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
        <li class="nav-item">
          <%= link_to "Root", root_path, class: "nav-link #{'active' if controller_name == 'dashboard'}" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= image_tag gravatar_image_url(current_user.email, size: 40, secure: true), height: 20, width: 20, class: "rounded" %>
            <% end %>
            <div aria-labelledby="navbar-dropdown" class="dropdown-menu dropdown-menu-right" id="nav-account-dropdown">
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>